all: sleep3_1 sleep3_2 sleep3_3 sleep3_4 sleep3_5 sleep3_6 sleep3_7 sleep3_8
sleep1_1:
	sleep 1
sleep1_2:
	sleep 5
sleep1_3:
	sleep 4
sleep2_1:	sleep1_1 sleep1_2 sleep1_3
	sleep 3
sleep2_2:	sleep1_1 sleep1_2 sleep1_3
	sleep 2
sleep2_3:	sleep1_1 sleep1_2 sleep1_3
	sleep 9
sleep2_4:	sleep1_1 sleep1_2 sleep1_3
	sleep 2
sleep2_5:	sleep1_1 sleep1_2 sleep1_3
	sleep 10
sleep3_1:	sleep2_1 sleep2_2 sleep2_3 sleep2_4 sleep2_5
	sleep 1
sleep3_2:	sleep2_1 sleep2_2 sleep2_3 sleep2_4 sleep2_5
	sleep 1
sleep3_3:	sleep2_1 sleep2_2 sleep2_3 sleep2_4 sleep2_5
	sleep 2
sleep3_4:	sleep2_1 sleep2_2 sleep2_3 sleep2_4 sleep2_5
	sleep 4
sleep3_5:	sleep2_1 sleep2_2 sleep2_3 sleep2_4 sleep2_5
	sleep 4
sleep3_6:	sleep2_1 sleep2_2 sleep2_3 sleep2_4 sleep2_5
	sleep 9
sleep3_7:	sleep2_1 sleep2_2 sleep2_3 sleep2_4 sleep2_5
	sleep 10
sleep3_8:	sleep2_1 sleep2_2 sleep2_3 sleep2_4 sleep2_5
	sleep 1
