stage1:
	@echo "hhh" > stage1.txt
stage2:
	@echo "hhh" > stage2.txt
stage3:
	@echo "hhh" > stage3.txt
stage4:
	@echo "hhh" > stage4.txt
stage5:
	@echo "hhh" > stage5.txt
stage6:
	@echo "hhh" > stage6.txt
stage7:
	@echo "hhh" > stage7.txt
stage8:
	@echo "hhh" > stage8.txt
stage9:
	@echo "hhh" > stage9.txt
stage10:
	@echo "hhh" > stage10.txt
stage11:
	@echo "hhh" > stage11.txt
stage12:
	@echo "hhh" > stage12.txt
stage13:
	@echo "hhh" > stage13.txt
stage14:
	@echo "hhh" > stage14.txt
stage15:
	@echo "hhh" > stage15.txt
stage16:
	@echo "hhh" > stage16.txt
stage17:
	@echo "hhh" > stage17.txt
stage18:
	@echo "hhh" > stage18.txt
stage19:
	@echo "hhh" > stage19.txt
stage20:
	@echo "hhh" > stage20.txt
