stage1:
	echo "hhh" > stage1.txt
stage2:
	echo "hhh" > stage2.txt
stage3:
	echo "hhh" > stage3.txt
stage4:
	echo "hhh" > stage4.txt
stage5:
	echo "hhh" > stage5.txt
stage6:
	echo "hhh" > stage6.txt
stage7:
	echo "hhh" > stage7.txt
stage8:
	echo "hhh" > stage8.txt
stage9:
	echo "hhh" > stage9.txt
stage10:
	echo "hhh" > stage10.txt
stage11:
	echo "hhh" > stage11.txt
stage12:
	echo "hhh" > stage12.txt
stage13:
	echo "hhh" > stage13.txt
stage14:
	echo "hhh" > stage14.txt
stage15:
	echo "hhh" > stage15.txt
stage16:
	echo "hhh" > stage16.txt
stage17:
	echo "hhh" > stage17.txt
stage18:
	echo "hhh" > stage18.txt
stage19:
	echo "hhh" > stage19.txt
stage20:
	echo "hhh" > stage20.txt
stage21:
	echo "hhh" > stage21.txt
stage22:
	echo "hhh" > stage22.txt
stage23:
	echo "hhh" > stage23.txt
stage24:
	echo "hhh" > stage24.txt
stage25:
	echo "hhh" > stage25.txt
stage26:
	echo "hhh" > stage26.txt
stage27:
	echo "hhh" > stage27.txt
stage28:
	echo "hhh" > stage28.txt
stage29:
	echo "hhh" > stage29.txt
stage30:
	echo "hhh" > stage30.txt
stage31:
	echo "hhh" > stage31.txt
stage32:
	echo "hhh" > stage32.txt
stage33:
	echo "hhh" > stage33.txt
stage34:
	echo "hhh" > stage34.txt
stage35:
	echo "hhh" > stage35.txt
stage36:
	echo "hhh" > stage36.txt
stage37:
	echo "hhh" > stage37.txt
stage38:
	echo "hhh" > stage38.txt
stage39:
	echo "hhh" > stage39.txt
stage40:
	echo "hhh" > stage40.txt
stage41:
	echo "hhh" > stage41.txt
stage42:
	echo "hhh" > stage42.txt
stage43:
	echo "hhh" > stage43.txt
stage44:
	echo "hhh" > stage44.txt
stage45:
	echo "hhh" > stage45.txt
stage46:
	echo "hhh" > stage46.txt
stage47:
	echo "hhh" > stage47.txt
stage48:
	echo "hhh" > stage48.txt
stage49:
	echo "hhh" > stage49.txt
stage50:
	echo "hhh" > stage50.txt
stage51:
	echo "hhh" > stage51.txt
stage52:
	echo "hhh" > stage52.txt
stage53:
	echo "hhh" > stage53.txt
stage54:
	echo "hhh" > stage54.txt
stage55:
	echo "hhh" > stage55.txt
stage56:
	echo "hhh" > stage56.txt
stage57:
	echo "hhh" > stage57.txt
stage58:
	echo "hhh" > stage58.txt
stage59:
	echo "hhh" > stage59.txt
stage60:
	echo "hhh" > stage60.txt
stage61:
	echo "hhh" > stage61.txt
stage62:
	echo "hhh" > stage62.txt
stage63:
	echo "hhh" > stage63.txt
stage64:
	echo "hhh" > stage64.txt
stage65:
	echo "hhh" > stage65.txt
stage66:
	echo "hhh" > stage66.txt
stage67:
	echo "hhh" > stage67.txt
stage68:
	echo "hhh" > stage68.txt
stage69:
	echo "hhh" > stage69.txt
stage70:
	echo "hhh" > stage70.txt
stage71:
	echo "hhh" > stage71.txt
stage72:
	echo "hhh" > stage72.txt
stage73:
	echo "hhh" > stage73.txt
stage74:
	echo "hhh" > stage74.txt
stage75:
	echo "hhh" > stage75.txt
stage76:
	echo "hhh" > stage76.txt
stage77:
	echo "hhh" > stage77.txt
stage78:
	echo "hhh" > stage78.txt
stage79:
	echo "hhh" > stage79.txt
stage80:
	echo "hhh" > stage80.txt
stage81:
	echo "hhh" > stage81.txt
stage82:
	echo "hhh" > stage82.txt
stage83:
	echo "hhh" > stage83.txt
stage84:
	echo "hhh" > stage84.txt
stage85:
	echo "hhh" > stage85.txt
stage86:
	echo "hhh" > stage86.txt
stage87:
	echo "hhh" > stage87.txt
stage88:
	echo "hhh" > stage88.txt
stage89:
	echo "hhh" > stage89.txt
stage90:
	echo "hhh" > stage90.txt
stage91:
	echo "hhh" > stage91.txt
stage92:
	echo "hhh" > stage92.txt
stage93:
	echo "hhh" > stage93.txt
stage94:
	echo "hhh" > stage94.txt
stage95:
	echo "hhh" > stage95.txt
stage96:
	echo "hhh" > stage96.txt
stage97:
	echo "hhh" > stage97.txt
stage98:
	echo "hhh" > stage98.txt
stage99:
	echo "hhh" > stage99.txt
stage100:
	echo "hhh" > stage100.txt
